name: Deploy Frontend to Coolify

on:
  push:
    branches:
      - v1
    paths:
      - 'apps/frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/frontend/Dockerfile
          push: true
          tags: ghcr.io/enxgin/beu-frontend:latest

      - name: Trigger Coolify deployment
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{}' ${{ secrets.COOLIFY_WEBHOOK_URL }}